// GENERATED by scripts/gen-illustrations.mjs — do not edit by hand.
// Run `npm run gen:illustrations` to refresh after changing the art set.
//
// The single typed catalogue every <Illustration> / <Sprout> reads. It carries
// only structural data (id, served path, category, intrinsic pixel size); the
// accessible ALT TEXT lives in next-intl messages so it is bilingual (EN/FR),
// keyed by id as `Illustrations.alt.<category>.<name>`.

export type IllustrationId =
  | 'characters/blue-waving'
  | 'characters/blue-with-coin'
  | 'characters/grape'
  | 'characters/green-with-coin'
  | 'characters/green-with-coins'
  | 'concepts/balance'
  | 'concepts/bounce-back'
  | 'concepts/compounding'
  | 'concepts/diversification'
  | 'concepts/dividends'
  | 'concepts/etf'
  | 'concepts/interest'
  | 'concepts/market-ups-and-downs'
  | 'concepts/markets-app'
  | 'concepts/risk-vs-reward'
  | 'concepts/stocks-vs-bonds'
  | 'concepts/time-in-market'
  | 'goals/build-wealth'
  | 'goals/childrens-future'
  | 'goals/dream-purchase'
  | 'goals/education'
  | 'goals/home-deposit'
  | 'goals/independence'
  | 'goals/retirement'
  | 'goals/safety-net'
  | 'mascot/arms-out'
  | 'mascot/balancing-beam'
  | 'mascot/calm'
  | 'mascot/catching-star'
  | 'mascot/celebrating'
  | 'mascot/cheering'
  | 'mascot/climbing'
  | 'mascot/coin-trail'
  | 'mascot/growth-arrow'
  | 'mascot/holding-sign'
  | 'mascot/jumping'
  | 'mascot/jumping-alt'
  | 'mascot/matterhorn'
  | 'mascot/pointing'
  | 'mascot/pushing-coin'
  | 'mascot/pushing-coin-alt'
  | 'mascot/reading'
  | 'mascot/relaxing-deckchair'
  | 'mascot/riding-wave'
  | 'mascot/sleeping'
  | 'mascot/thinking'
  | 'mascot/thinking-bubble'
  | 'mascot/thumbs-up'
  | 'mascot/watering'
  | 'mascot/with-clock-plant'
  | 'mascot/with-globe'
  | 'mascot/with-magnifier'
  | 'mascot/with-pie-chart'
  | 'mascot/with-trophy'
  | 'money/emergency-fund'
  | 'money/monthly-saving'
  | 'money/piggy-bank'
  | 'money/piggy-bank-coin'
  | 'money/savings-jar'
  | 'scenes/goal-reached'
  | 'scenes/welcome'
  | 'sectors/clean-energy'
  | 'sectors/consumer-discretionary'
  | 'sectors/consumer-staples'
  | 'sectors/financials'
  | 'sectors/financials-alt'
  | 'sectors/healthcare'
  | 'sectors/materials'
  | 'sectors/real-estate'
  | 'sectors/technology'
  | 'sectors/utilities'
  | 'sky/balloon'
  | 'sky/bird'
  | 'sky/cloud-big'
  | 'sky/cloud-filled'
  | 'sky/cloud-outline'
  | 'sky/cloud-wide'
  | 'sky/hot-air-balloon'
  | 'sky/rainbow'
  | 'sky/sparkles'
  | 'sky/sun'
  | 'sky/sun-spark'
  | 'switzerland/protected'
  | 'switzerland/swiss-coin';

export type IllustrationCategory = 'characters' | 'concepts' | 'goals' | 'mascot' | 'money' | 'scenes' | 'sectors' | 'sky' | 'switzerland';

/** The Sprout mascot poses (the `mascot/` ids, prefix stripped). */
export type SproutPose =
  | 'arms-out'
  | 'balancing-beam'
  | 'calm'
  | 'catching-star'
  | 'celebrating'
  | 'cheering'
  | 'climbing'
  | 'coin-trail'
  | 'growth-arrow'
  | 'holding-sign'
  | 'jumping'
  | 'jumping-alt'
  | 'matterhorn'
  | 'pointing'
  | 'pushing-coin'
  | 'pushing-coin-alt'
  | 'reading'
  | 'relaxing-deckchair'
  | 'riding-wave'
  | 'sleeping'
  | 'thinking'
  | 'thinking-bubble'
  | 'thumbs-up'
  | 'watering'
  | 'with-clock-plant'
  | 'with-globe'
  | 'with-magnifier'
  | 'with-pie-chart'
  | 'with-trophy';

export interface IllustrationMeta {
  /** Catalogue id, e.g. `mascot/thinking`. */
  readonly id: IllustrationId;
  /** Path served from /public, e.g. `/illustrations/mascot/thinking.svg`. */
  readonly src: string;
  readonly category: IllustrationCategory;
  /** Intrinsic pixel width — drives the aspect ratio (no layout shift). */
  readonly width: number;
  /** Intrinsic pixel height. */
  readonly height: number;
}

export const ILLUSTRATIONS: readonly IllustrationMeta[] = [
  {id: 'characters/blue-waving', src: '/illustrations/characters/blue-waving.svg', category: 'characters', width: 803, height: 659},
  {id: 'characters/blue-with-coin', src: '/illustrations/characters/blue-with-coin.svg', category: 'characters', width: 601, height: 573},
  {id: 'characters/grape', src: '/illustrations/characters/grape.svg', category: 'characters', width: 691, height: 627},
  {id: 'characters/green-with-coin', src: '/illustrations/characters/green-with-coin.svg', category: 'characters', width: 653, height: 573},
  {id: 'characters/green-with-coins', src: '/illustrations/characters/green-with-coins.svg', category: 'characters', width: 871, height: 619},
  {id: 'concepts/balance', src: '/illustrations/concepts/balance.svg', category: 'concepts', width: 758, height: 745},
  {id: 'concepts/bounce-back', src: '/illustrations/concepts/bounce-back.svg', category: 'concepts', width: 722, height: 706},
  {id: 'concepts/compounding', src: '/illustrations/concepts/compounding.svg', category: 'concepts', width: 1044, height: 1084},
  {id: 'concepts/diversification', src: '/illustrations/concepts/diversification.svg', category: 'concepts', width: 1046, height: 617},
  {id: 'concepts/dividends', src: '/illustrations/concepts/dividends.svg', category: 'concepts', width: 785, height: 834},
  {id: 'concepts/etf', src: '/illustrations/concepts/etf.svg', category: 'concepts', width: 700, height: 630},
  {id: 'concepts/interest', src: '/illustrations/concepts/interest.svg', category: 'concepts', width: 713, height: 737},
  {id: 'concepts/market-ups-and-downs', src: '/illustrations/concepts/market-ups-and-downs.svg', category: 'concepts', width: 723, height: 598},
  {id: 'concepts/markets-app', src: '/illustrations/concepts/markets-app.svg', category: 'concepts', width: 669, height: 737},
  {id: 'concepts/risk-vs-reward', src: '/illustrations/concepts/risk-vs-reward.svg', category: 'concepts', width: 992, height: 467},
  {id: 'concepts/stocks-vs-bonds', src: '/illustrations/concepts/stocks-vs-bonds.svg', category: 'concepts', width: 879, height: 390},
  {id: 'concepts/time-in-market', src: '/illustrations/concepts/time-in-market.svg', category: 'concepts', width: 661, height: 620},
  {id: 'goals/build-wealth', src: '/illustrations/goals/build-wealth.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/childrens-future', src: '/illustrations/goals/childrens-future.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/dream-purchase', src: '/illustrations/goals/dream-purchase.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/education', src: '/illustrations/goals/education.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/home-deposit', src: '/illustrations/goals/home-deposit.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/independence', src: '/illustrations/goals/independence.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/retirement', src: '/illustrations/goals/retirement.png', category: 'goals', width: 512, height: 512},
  {id: 'goals/safety-net', src: '/illustrations/goals/safety-net.png', category: 'goals', width: 512, height: 512},
  {id: 'mascot/arms-out', src: '/illustrations/mascot/arms-out.svg', category: 'mascot', width: 690, height: 651},
  {id: 'mascot/balancing-beam', src: '/illustrations/mascot/balancing-beam.svg', category: 'mascot', width: 690, height: 839},
  {id: 'mascot/calm', src: '/illustrations/mascot/calm.svg', category: 'mascot', width: 632, height: 682},
  {id: 'mascot/catching-star', src: '/illustrations/mascot/catching-star.svg', category: 'mascot', width: 714, height: 768},
  {id: 'mascot/celebrating', src: '/illustrations/mascot/celebrating.svg', category: 'mascot', width: 1033, height: 811},
  {id: 'mascot/cheering', src: '/illustrations/mascot/cheering.svg', category: 'mascot', width: 697, height: 769},
  {id: 'mascot/climbing', src: '/illustrations/mascot/climbing.svg', category: 'mascot', width: 704, height: 883},
  {id: 'mascot/coin-trail', src: '/illustrations/mascot/coin-trail.svg', category: 'mascot', width: 727, height: 706},
  {id: 'mascot/growth-arrow', src: '/illustrations/mascot/growth-arrow.svg', category: 'mascot', width: 742, height: 530},
  {id: 'mascot/holding-sign', src: '/illustrations/mascot/holding-sign.svg', category: 'mascot', width: 679, height: 614},
  {id: 'mascot/jumping', src: '/illustrations/mascot/jumping.svg', category: 'mascot', width: 733, height: 778},
  {id: 'mascot/jumping-alt', src: '/illustrations/mascot/jumping-alt.svg', category: 'mascot', width: 718, height: 718},
  {id: 'mascot/matterhorn', src: '/illustrations/mascot/matterhorn.svg', category: 'mascot', width: 760, height: 658},
  {id: 'mascot/pointing', src: '/illustrations/mascot/pointing.svg', category: 'mascot', width: 605, height: 701},
  {id: 'mascot/pushing-coin', src: '/illustrations/mascot/pushing-coin.svg', category: 'mascot', width: 732, height: 610},
  {id: 'mascot/pushing-coin-alt', src: '/illustrations/mascot/pushing-coin-alt.svg', category: 'mascot', width: 728, height: 777},
  {id: 'mascot/reading', src: '/illustrations/mascot/reading.svg', category: 'mascot', width: 666, height: 665},
  {id: 'mascot/relaxing-deckchair', src: '/illustrations/mascot/relaxing-deckchair.svg', category: 'mascot', width: 584, height: 720},
  {id: 'mascot/riding-wave', src: '/illustrations/mascot/riding-wave.svg', category: 'mascot', width: 1016, height: 589},
  {id: 'mascot/sleeping', src: '/illustrations/mascot/sleeping.svg', category: 'mascot', width: 622, height: 586},
  {id: 'mascot/thinking', src: '/illustrations/mascot/thinking.svg', category: 'mascot', width: 702, height: 690},
  {id: 'mascot/thinking-bubble', src: '/illustrations/mascot/thinking-bubble.svg', category: 'mascot', width: 862, height: 527},
  {id: 'mascot/thumbs-up', src: '/illustrations/mascot/thumbs-up.svg', category: 'mascot', width: 651, height: 694},
  {id: 'mascot/watering', src: '/illustrations/mascot/watering.svg', category: 'mascot', width: 842, height: 612},
  {id: 'mascot/with-clock-plant', src: '/illustrations/mascot/with-clock-plant.svg', category: 'mascot', width: 672, height: 706},
  {id: 'mascot/with-globe', src: '/illustrations/mascot/with-globe.svg', category: 'mascot', width: 691, height: 839},
  {id: 'mascot/with-magnifier', src: '/illustrations/mascot/with-magnifier.svg', category: 'mascot', width: 577, height: 671},
  {id: 'mascot/with-pie-chart', src: '/illustrations/mascot/with-pie-chart.svg', category: 'mascot', width: 727, height: 592},
  {id: 'mascot/with-trophy', src: '/illustrations/mascot/with-trophy.svg', category: 'mascot', width: 684, height: 717},
  {id: 'money/emergency-fund', src: '/illustrations/money/emergency-fund.svg', category: 'money', width: 681, height: 801},
  {id: 'money/monthly-saving', src: '/illustrations/money/monthly-saving.svg', category: 'money', width: 600, height: 596},
  {id: 'money/piggy-bank', src: '/illustrations/money/piggy-bank.svg', category: 'money', width: 612, height: 541},
  {id: 'money/piggy-bank-coin', src: '/illustrations/money/piggy-bank-coin.svg', category: 'money', width: 842, height: 715},
  {id: 'money/savings-jar', src: '/illustrations/money/savings-jar.svg', category: 'money', width: 665, height: 1385},
  {id: 'scenes/goal-reached', src: '/illustrations/scenes/goal-reached.svg', category: 'scenes', width: 694, height: 706},
  {id: 'scenes/welcome', src: '/illustrations/scenes/welcome.svg', category: 'scenes', width: 1060, height: 811},
  {id: 'sectors/clean-energy', src: '/illustrations/sectors/clean-energy.svg', category: 'sectors', width: 521, height: 563},
  {id: 'sectors/consumer-discretionary', src: '/illustrations/sectors/consumer-discretionary.svg', category: 'sectors', width: 705, height: 584},
  {id: 'sectors/consumer-staples', src: '/illustrations/sectors/consumer-staples.svg', category: 'sectors', width: 674, height: 760},
  {id: 'sectors/financials', src: '/illustrations/sectors/financials.svg', category: 'sectors', width: 775, height: 652},
  {id: 'sectors/financials-alt', src: '/illustrations/sectors/financials-alt.svg', category: 'sectors', width: 1118, height: 754},
  {id: 'sectors/healthcare', src: '/illustrations/sectors/healthcare.svg', category: 'sectors', width: 581, height: 726},
  {id: 'sectors/materials', src: '/illustrations/sectors/materials.svg', category: 'sectors', width: 468, height: 563},
  {id: 'sectors/real-estate', src: '/illustrations/sectors/real-estate.svg', category: 'sectors', width: 653, height: 573},
  {id: 'sectors/technology', src: '/illustrations/sectors/technology.svg', category: 'sectors', width: 674, height: 783},
  {id: 'sectors/utilities', src: '/illustrations/sectors/utilities.svg', category: 'sectors', width: 507, height: 563},
  {id: 'sky/balloon', src: '/illustrations/sky/balloon.svg', category: 'sky', width: 609, height: 795},
  {id: 'sky/bird', src: '/illustrations/sky/bird.svg', category: 'sky', width: 504, height: 414},
  {id: 'sky/cloud-big', src: '/illustrations/sky/cloud-big.svg', category: 'sky', width: 863, height: 746},
  {id: 'sky/cloud-filled', src: '/illustrations/sky/cloud-filled.svg', category: 'sky', width: 630, height: 557},
  {id: 'sky/cloud-outline', src: '/illustrations/sky/cloud-outline.svg', category: 'sky', width: 994, height: 485},
  {id: 'sky/cloud-wide', src: '/illustrations/sky/cloud-wide.svg', category: 'sky', width: 1089, height: 474},
  {id: 'sky/hot-air-balloon', src: '/illustrations/sky/hot-air-balloon.svg', category: 'sky', width: 605, height: 933},
  {id: 'sky/rainbow', src: '/illustrations/sky/rainbow.svg', category: 'sky', width: 954, height: 496},
  {id: 'sky/sparkles', src: '/illustrations/sky/sparkles.svg', category: 'sky', width: 497, height: 782},
  {id: 'sky/sun', src: '/illustrations/sky/sun.svg', category: 'sky', width: 605, height: 628},
  {id: 'sky/sun-spark', src: '/illustrations/sky/sun-spark.svg', category: 'sky', width: 625, height: 607},
  {id: 'switzerland/protected', src: '/illustrations/switzerland/protected.svg', category: 'switzerland', width: 764, height: 737},
  {id: 'switzerland/swiss-coin', src: '/illustrations/switzerland/swiss-coin.svg', category: 'switzerland', width: 764, height: 596}
];

export const ILLUSTRATION_BY_ID: Record<IllustrationId, IllustrationMeta> =
  Object.fromEntries(ILLUSTRATIONS.map((i) => [i.id, i])) as Record<
    IllustrationId,
    IllustrationMeta
  >;

export const ILLUSTRATION_CATEGORIES: readonly IllustrationCategory[] = [
  'characters', 'concepts', 'goals', 'mascot', 'money', 'scenes', 'sectors', 'sky', 'switzerland'
];

/** Every Sprout pose, sorted — drives the typed `<Sprout pose>` prop. */
export const SPROUT_POSES: readonly SproutPose[] = [
  'arms-out', 'balancing-beam', 'calm', 'catching-star', 'celebrating', 'cheering', 'climbing', 'coin-trail', 'growth-arrow', 'holding-sign', 'jumping', 'jumping-alt', 'matterhorn', 'pointing', 'pushing-coin', 'pushing-coin-alt', 'reading', 'relaxing-deckchair', 'riding-wave', 'sleeping', 'thinking', 'thinking-bubble', 'thumbs-up', 'watering', 'with-clock-plant', 'with-globe', 'with-magnifier', 'with-pie-chart', 'with-trophy'
];
